### ISSUE TITLE
[Feature] Automatically detect static files and move them to respective folders

### ISSUE THREAD

**Issue by amartya-dev** [L4TTiCe/djangify#3]
# The problem
Currently, the scripts only change the references to the CSS or other static files and then the user would manually have to move the files in the required folder.

# Tasks for adding the feature
- [ ] Keep track of the files discovered files (possibly log them)
- [ ] Ask if the person wants to move the said files to his project directory
- [ ] Get the path of the project directory to move it directly to the project OR
- [ ] Make a static folder called static with the app_name folder in it, and the user can later copy that as per requirement.

**Comment by Jeketam** [comment]
Hi, can I pick up this issue?

**Comment by amartya-dev** [comment]
@Jeketam sure, go-ahead 

Just add some pointers here on how you are thinking of handling this...

**Comment by Jeketam** [comment]
For tracking the discovered files I was thinking of printing the locations to the console.

The option to move the files automatically or create app_name/static folder would be handled via argument in the command.

Does that sound alright?

**Comment by amartya-dev** [comment]
I do not think I understand what you are trying to do here:

- Yes the second point is correct, we would need to give the user an option to move the files, the files have to be moved to folders according to the `app_name` flag given by the user, if no such flag is given then the files would have to go in a `static` folder. All the static files will have to be copied while preserving their directory structure for this to work. 

- I do not understand how you would be tracking files by printing them, could you please elaborate a bit more on that?  

If you think you have got it right, go ahead and make a PR, I would like to see how you are handling this.
